package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.CrawlTest;
import com.unbank.db.mybatis.vo.CrawlTestExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlTestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int countByExample(CrawlTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByExample(CrawlTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insert(CrawlTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insertSelective(CrawlTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	List<CrawlTest> selectByExample(CrawlTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	CrawlTest selectByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") CrawlTest record,
			@Param("example") CrawlTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExample(@Param("record") CrawlTest record,
			@Param("example") CrawlTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKeySelective(CrawlTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_test
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKey(CrawlTest record);
}