package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.Crawl;
import com.unbank.db.mybatis.vo.CrawlExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int countByExample(CrawlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByExample(CrawlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insert(Crawl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insertSelective(Crawl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	List<Crawl> selectByExample(CrawlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	Crawl selectByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Crawl record,
			@Param("example") CrawlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExample(@Param("record") Crawl record,
			@Param("example") CrawlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKeySelective(Crawl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKey(Crawl record);
}