package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.DayNumWeb;
import com.unbank.db.mybatis.vo.DayNumWebExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayNumWebMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int countByExample(DayNumWebExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByExample(DayNumWebExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insert(DayNumWeb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insertSelective(DayNumWeb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	List<DayNumWeb> selectByExample(DayNumWebExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	DayNumWeb selectByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") DayNumWeb record,
			@Param("example") DayNumWebExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExample(@Param("record") DayNumWeb record,
			@Param("example") DayNumWebExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKeySelective(DayNumWeb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKey(DayNumWeb record);
}