package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.DayNumSyn;
import com.unbank.db.mybatis.vo.DayNumSynExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayNumSynMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int countByExample(DayNumSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByExample(DayNumSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insert(DayNumSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insertSelective(DayNumSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	List<DayNumSyn> selectByExample(DayNumSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	DayNumSyn selectByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") DayNumSyn record,
			@Param("example") DayNumSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExample(@Param("record") DayNumSyn record,
			@Param("example") DayNumSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKeySelective(DayNumSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKey(DayNumSyn record);
}