package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.DayNumDup;
import com.unbank.db.mybatis.vo.DayNumDupExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayNumDupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int countByExample(DayNumDupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int deleteByExample(DayNumDupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int deleteByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int insert(DayNumDup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int insertSelective(DayNumDup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    List<DayNumDup> selectByExample(DayNumDupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    DayNumDup selectByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") DayNumDup record, @Param("example") DayNumDupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int updateByExample(@Param("record") DayNumDup record, @Param("example") DayNumDupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int updateByPrimaryKeySelective(DayNumDup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_dup
     *
     * @mbggenerated Fri Dec 12 10:54:58 CST 2014
     */
    int updateByPrimaryKey(DayNumDup record);
}