package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.DayNumWebSyn;
import com.unbank.db.mybatis.vo.DayNumWebSynExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayNumWebSynMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int countByExample(DayNumWebSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByExample(DayNumWebSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insert(DayNumWebSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int insertSelective(DayNumWebSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	List<DayNumWebSyn> selectByExample(DayNumWebSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	DayNumWebSyn selectByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") DayNumWebSyn record,
			@Param("example") DayNumWebSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByExample(@Param("record") DayNumWebSyn record,
			@Param("example") DayNumWebSynExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKeySelective(DayNumWebSyn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num_web_syn
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	int updateByPrimaryKey(DayNumWebSyn record);
}