package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.MonitorCrawlNumError;
import com.unbank.db.mybatis.vo.MonitorCrawlNumErrorExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonitorCrawlNumErrorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int countByExample(MonitorCrawlNumErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int deleteByExample(MonitorCrawlNumErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int insert(MonitorCrawlNumError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int insertSelective(MonitorCrawlNumError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	List<MonitorCrawlNumError> selectByExample(
			MonitorCrawlNumErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	MonitorCrawlNumError selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") MonitorCrawlNumError record,
			@Param("example") MonitorCrawlNumErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") MonitorCrawlNumError record,
			@Param("example") MonitorCrawlNumErrorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(MonitorCrawlNumError record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_monitor_numerror
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	int updateByPrimaryKey(MonitorCrawlNumError record);
}