package com.unbank.db.mybatis.client;

import com.unbank.db.mybatis.vo.WebsiteParser;
import com.unbank.db.mybatis.vo.WebsiteParserExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteParserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int countByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int deleteByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int deleteByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int insert(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int insertSelective(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    List<WebsiteParser> selectByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    WebsiteParser selectByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") WebsiteParser record, @Param("example") WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int updateByExample(@Param("record") WebsiteParser record, @Param("example") WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int updateByPrimaryKeySelective(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Dec 10 16:09:21 CST 2014
     */
    int updateByPrimaryKey(WebsiteParser record);
}