package com.unbank.db.mybatis.vo;

public class DayNumSyn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_syn.num_id
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	private Integer numId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_syn.crawl_time
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	private String crawlTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_syn.num
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_syn.num_id
	 * @return  the value of ptf_day_num_syn.num_id
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public Integer getNumId() {
		return numId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_syn.num_id
	 * @param numId  the value for ptf_day_num_syn.num_id
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public void setNumId(Integer numId) {
		this.numId = numId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_syn.crawl_time
	 * @return  the value of ptf_day_num_syn.crawl_time
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public String getCrawlTime() {
		return crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_syn.crawl_time
	 * @param crawlTime  the value for ptf_day_num_syn.crawl_time
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public void setCrawlTime(String crawlTime) {
		this.crawlTime = crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_syn.num
	 * @return  the value of ptf_day_num_syn.num
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_syn.num
	 * @param num  the value for ptf_day_num_syn.num
	 * @mbggenerated  Tue Dec 02 10:33:10 CST 2014
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}