package com.unbank.db.mybatis.vo;

import java.util.Date;

public class MonitorCrawlNumError {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.id
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.websiteid
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Integer websiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.avage_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Integer avageNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.pro_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Integer proNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.crawl_time
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Date crawlTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.status
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_monitor_numerror.url
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.id
	 * @return  the value of ptf_monitor_numerror.id
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.id
	 * @param id  the value for ptf_monitor_numerror.id
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.websiteid
	 * @return  the value of ptf_monitor_numerror.websiteid
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Integer getWebsiteid() {
		return websiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.websiteid
	 * @param websiteid  the value for ptf_monitor_numerror.websiteid
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setWebsiteid(Integer websiteid) {
		this.websiteid = websiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.avage_num
	 * @return  the value of ptf_monitor_numerror.avage_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Integer getAvageNum() {
		return avageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.avage_num
	 * @param avageNum  the value for ptf_monitor_numerror.avage_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setAvageNum(Integer avageNum) {
		this.avageNum = avageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.pro_num
	 * @return  the value of ptf_monitor_numerror.pro_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Integer getProNum() {
		return proNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.pro_num
	 * @param proNum  the value for ptf_monitor_numerror.pro_num
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setProNum(Integer proNum) {
		this.proNum = proNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.crawl_time
	 * @return  the value of ptf_monitor_numerror.crawl_time
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Date getCrawlTime() {
		return crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.crawl_time
	 * @param crawlTime  the value for ptf_monitor_numerror.crawl_time
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setCrawlTime(Date crawlTime) {
		this.crawlTime = crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.status
	 * @return  the value of ptf_monitor_numerror.status
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.status
	 * @param status  the value for ptf_monitor_numerror.status
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_monitor_numerror.url
	 * @return  the value of ptf_monitor_numerror.url
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_monitor_numerror.url
	 * @param url  the value for ptf_monitor_numerror.url
	 * @mbggenerated  Fri Mar 06 17:33:02 GMT+08:00 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}