package com.unbank.db.mybatis.vo;

import java.util.Date;

public class MonitorUrlError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.id
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.websiteid
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private Integer websiteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.url
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.check_time
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.status
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.http_code
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private Integer httpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_monitor_urlerror.error_info
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    private String errorInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.id
     *
     * @return the value of ptf_monitor_urlerror.id
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.id
     *
     * @param id the value for ptf_monitor_urlerror.id
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.websiteid
     *
     * @return the value of ptf_monitor_urlerror.websiteid
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public Integer getWebsiteid() {
        return websiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.websiteid
     *
     * @param websiteid the value for ptf_monitor_urlerror.websiteid
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setWebsiteid(Integer websiteid) {
        this.websiteid = websiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.url
     *
     * @return the value of ptf_monitor_urlerror.url
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.url
     *
     * @param url the value for ptf_monitor_urlerror.url
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.check_time
     *
     * @return the value of ptf_monitor_urlerror.check_time
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.check_time
     *
     * @param checkTime the value for ptf_monitor_urlerror.check_time
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.status
     *
     * @return the value of ptf_monitor_urlerror.status
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.status
     *
     * @param status the value for ptf_monitor_urlerror.status
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.http_code
     *
     * @return the value of ptf_monitor_urlerror.http_code
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public Integer getHttpCode() {
        return httpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.http_code
     *
     * @param httpCode the value for ptf_monitor_urlerror.http_code
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setHttpCode(Integer httpCode) {
        this.httpCode = httpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_monitor_urlerror.error_info
     *
     * @return the value of ptf_monitor_urlerror.error_info
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_monitor_urlerror.error_info
     *
     * @param errorInfo the value for ptf_monitor_urlerror.error_info
     *
     * @mbggenerated Wed Mar 04 15:15:18 GMT+08:00 2015
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo;
    }
}