package com.unbank.db.mybatis.vo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_id
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_name
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_pwd
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_permission
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private String userPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_pid
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private Integer userPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_department
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private String userDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user.user_reg_time
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    private Date userRegTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_id
     *
     * @return the value of ptf_user.user_id
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_id
     *
     * @param userId the value for ptf_user.user_id
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_name
     *
     * @return the value of ptf_user.user_name
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_name
     *
     * @param userName the value for ptf_user.user_name
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_pwd
     *
     * @return the value of ptf_user.user_pwd
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_pwd
     *
     * @param userPwd the value for ptf_user.user_pwd
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_permission
     *
     * @return the value of ptf_user.user_permission
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public String getUserPermission() {
        return userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_permission
     *
     * @param userPermission the value for ptf_user.user_permission
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserPermission(String userPermission) {
        this.userPermission = userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_pid
     *
     * @return the value of ptf_user.user_pid
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public Integer getUserPid() {
        return userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_pid
     *
     * @param userPid the value for ptf_user.user_pid
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserPid(Integer userPid) {
        this.userPid = userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_department
     *
     * @return the value of ptf_user.user_department
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public String getUserDepartment() {
        return userDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_department
     *
     * @param userDepartment the value for ptf_user.user_department
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserDepartment(String userDepartment) {
        this.userDepartment = userDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user.user_reg_time
     *
     * @return the value of ptf_user.user_reg_time
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public Date getUserRegTime() {
        return userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user.user_reg_time
     *
     * @param userRegTime the value for ptf_user.user_reg_time
     *
     * @mbggenerated Tue Jan 13 10:47:10 CST 2015
     */
    public void setUserRegTime(Date userRegTime) {
        this.userRegTime = userRegTime;
    }

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName + ", userPwd=" + userPwd + ", userPermission="
				+ userPermission + ", userPid=" + userPid + ", userDepartment=" + userDepartment + ", userRegTime="
				+ userRegTime + "]";
	}
    
}