package com.unbank.db.mybatis.vo;

import java.util.Date;

public class UserOpt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.opt_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private Integer optId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.user_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.website_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.opt_type
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.opt_time
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private Date optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_user_opt.opt_msg
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    private String optMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.opt_id
     *
     * @return the value of ptf_user_opt.opt_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public Integer getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.opt_id
     *
     * @param optId the value for ptf_user_opt.opt_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setOptId(Integer optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.user_id
     *
     * @return the value of ptf_user_opt.user_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.user_id
     *
     * @param userId the value for ptf_user_opt.user_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.website_id
     *
     * @return the value of ptf_user_opt.website_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.website_id
     *
     * @param websiteId the value for ptf_user_opt.website_id
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.opt_type
     *
     * @return the value of ptf_user_opt.opt_type
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.opt_type
     *
     * @param optType the value for ptf_user_opt.opt_type
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setOptType(String optType) {
        this.optType = optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.opt_time
     *
     * @return the value of ptf_user_opt.opt_time
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.opt_time
     *
     * @param optTime the value for ptf_user_opt.opt_time
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_user_opt.opt_msg
     *
     * @return the value of ptf_user_opt.opt_msg
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public String getOptMsg() {
        return optMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_user_opt.opt_msg
     *
     * @param optMsg the value for ptf_user_opt.opt_msg
     *
     * @mbggenerated Thu Mar 19 10:13:17 CST 2015
     */
    public void setOptMsg(String optMsg) {
        this.optMsg = optMsg;
    }
}